### ISSUE TITLE
Provide optional interfaces for users/groups

### ISSUE THREAD

**Issue by seeroush** [django-waffle/django-waffle#231] opened 2016-10-26 21:50 UTC
I would love to be able to use Waffle. However, the hard-wired dependency on Django's optional permission/group models makes it difficult, if not impossible to use for applications that have their own, custom model for groups. It would be nice to provide some interface, possibly as a model manager, to interact with custom group models rather than set a requirement on optional Django features.

Ex: 

```

# settings.py
WAFFLE_GROUP_MODEL = MyGroup

# waffle/models/Flag
groups = models.ManyToManyField(settings.WAFFLE_GROUP_MODEL, blank=True, help_text=(
        'Activate this flag for these user groups.'))
```

The fact that is_active() on the Flag model is always referencing a model that we don't use means that we have no way of flagging based on groups.

**Comment by jsocol** [comment] 2017-08-26 17:48
I think abstract base models are probably the right way to achieve this so I'm going to mark this as a duplicate of #181 for now.

**Comment by jsocol** [comment] 2017-08-26 17:48
Duplicate of #181 
(One day I will learn how to trigger this behavior correctly.)

**Closed as completed by jsocol** 2017-08-26 17:48 UTC
