### ISSUE TITLE
Class-based views support

### ISSUE THREAD

**Issue by ghost** [django-waffle/django-waffle#263] opened 2017-11-10 15:27 UTC
I see there is PR https://github.com/jsocol/django-waffle/pull/92 adding CBV support but it was closed by the stale bot. Is there any reason why the PR was not merge? Given how CBV are more and more standard way to make views in Django I find it a pitty that waffle does not come with the corresponding mixins. Is there anything I can to to help with getting the PR to merge?

**Comment by washeck** [comment] 2017-12-11 08:49
@jsocol Is there any preventing #92 from being merged?

**Comment by jsocol** [comment] 2017-12-31 22:42
Commented over on the PR, going to close this out as a duplicate of #92.

**Closed as completed by jsocol** 2017-12-31 22:42 UTC
