### ISSUE TITLE
automatic creating of models

### ISSUE THREAD

**Issue by oppianmatt** [django-waffle/django-waffle#238] opened 2016-12-14 11:11 UTC
Can we have an option that automatically creates the switches/flags/samples if they are checked? Don't want to have to go and create the models in the admin each time. If it could create a default switch (off), or a default flag (off for everyone) when it checks that would be better. Then can see in the admin what waffles are still being used/checked. If you delete one and it comes back then it's still in use somewhere.

**Comment by oppianmatt** [comment] 2016-12-14 11:15
Note this would improve performance as well as I noticed the code does a lookup for each flag. If it doesn't exist it never gets added to the cache so you always get the query.

```
    flag = cache.get(keyfmt(get_setting('FLAG_CACHE_KEY'), flag_name))
    if flag is None:
        try:
            flag = Flag.objects.get(name=flag_name)
            cache_flag(instance=flag)
        except Flag.DoesNotExist:
            return get_setting('FLAG_DEFAULT')
```

**Comment by jsocol** [comment] 2017-08-26 17:45
This is a duplicate of #44 and #45—that decision is still open but it's a goal to make a call before 1.0.

**Closed as completed by jsocol** 2017-08-26 17:45 UTC

**Comment by jsocol** [comment] 2017-08-26 17:46
Duplicate #44.

**Comment by jsocol** [comment] 2017-08-26 17:46
Duplicate of #44
