### ISSUE TITLE
Waffle middleware is failing on Django 1.10

### ISSUE THREAD

**Issue by avinassh** [django-waffle/django-waffle#232] opened 2016-10-31 11:39 UTC
Version details - Python v3.5.2, Django v1.10.2, Waffle v0.11.1

Added waffle to installed apps and middlewares as per docs. And I am getting this following error:

```
  Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10dc60488>
  Traceback (most recent call last):
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
      fn(*args, **kwargs)
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
      handler = self.get_handler(*args, **options)
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
      handler = super(Command, self).get_handler(*args, **options)
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
      return get_internal_wsgi_application()
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
      return import_string(app_path)
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
      module = import_module(module_path)
    File "/Users/avi/.virtualenvs/della/lib/python3.5/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 986, in _gcd_import
    File "<frozen importlib._bootstrap>", line 969, in _find_and_load
    File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 665, in exec_module
    File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
    File "/Users/avi/Documents/code/della/della/wsgi.py", line 16, in <module>
      application = get_wsgi_application()
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
      return WSGIHandler()
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
      self.load_middleware()
    File "/Users/avi/.virtualenvs/della/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
      mw_instance = middleware(handler)
  TypeError: object() takes no parameters
```

**Comment by aaugustin** [comment] 2016-11-09 14:57
I believe this is a duplicate of #223.

@jsocol Perhaps you could make a release to prevent more people from running into this on Django 1.10?

**Comment by joeyespo** [comment] 2016-11-25 20:20
Any update on a release? This is failing on Django 1.10.3 too.

**Comment by aaugustin** [comment] 2016-11-25 21:08
@joeyespo Undoubtedly it'll keep failing in future versions of Django until there's a new release of waffle.

**Comment by jsocol** [comment] 2017-01-16 18:09
Closing as a duplicate of #223—please reopen if there are still issues!

**Closed as completed by jsocol** 2017-01-16 18:09 UTC
