### ISSUE TITLE
What is missing for a new release with the fixes for django 1.10?

### ISSUE THREAD

**Issue by do3cc** [django-waffle/django-waffle#240] opened 2017-01-23 09:27 UTC
currently, I need to use the master branch to use the new style middleware class.
Are there other bugs related to 1.10 that need fixing before we get a new release?

**Comment by saily** [comment] 2017-01-23 21:53
@jsocol issues for a Django 1.10 compatible release are already bundled to [milestone 0.12](https://github.com/jsocol/django-waffle/milestone/6), right?

**Comment by aaugustin** [comment] 2017-03-15 12:59
None of these issues appear to be regressions from 0.11, so even if the current master branch can't claim full support for Django 1.10, it would be great to be able to start using new-style middleware in projects that depend on a released version of django-waffle.

**Comment by gbarbaten** [comment] 2017-04-11 10:04
I'm using django-waffle from the master branch in a Django 1.10 project with Python 3 and it works fine (i'm using switches, still not needed flags).

It will be great to have it published in Pypi to don't need to install from git

**Comment by gbarbaten** [comment] 2017-04-21 14:33
@saily @do3cc it seems that all issues are merged (#241 is merged, despite the issue is not closed).
I'm using the master branch version for several weeks and it works well.
If you need something else to publish it, tell me and if I can I help

**Comment by do3cc** [comment] 2017-04-25 12:31
@jsocol is the only one who can make a release. So we are all stuck with using the master branch until he either makes a new release or distributes the rights to commit and make release to more people.

**Comment by ncknuna** [comment] 2017-05-19 23:56
@jsocol Any update on when a new release could happen?

**Comment by do3cc** [comment] 2017-05-22 08:41
@jsocol Could you consider to increase the number of people with the rights to do releases?
As you can see, quite a few people are waiting for an update that currently only you can do.

**Comment by clintonb** [comment] 2017-06-28 02:19
Version 0.12.0 is now available on PyPI.

**Closed as completed by clintonb** 2017-06-28 02:19 UTC
