### ISSUE TITLE
Custom decision logic for flags

### ISSUE THREAD

**Issue by holvianssi** [django-waffle/django-waffle#234] opened 2016-11-03 13:57 UTC
It sometimes happens that you have some custom logic for enabling a flag. Some examples include:
  - Enable new login screen for internal IPs only (my use case right now)
  - Allow hand-pick of users for which the flag should be active (for example by setting a flag in User model)

One way to allow these is allowing running of custom code. A very short example of how to achieve this in waffle is as follows:
```
    # In the end of waffle.__init__.flag_is_active
    enabled = []

    def enable():
        enabled.append(True)

    enable_flag_signal.send(
        sender=None, request=request, flag=flag, enable=enable)

    return any(enabled)
```

And usage is as follows:
```
from waffle.signals import enable_flag_signal
from django.dispatch import receiver
from datetime import datetime

@receiver(enable_flag_signal)
def enable_bihourly(sender, request, flag, enable, **kwargs):
    if flag.name == 'new_login':
        if datetime.now().hour % 2 == 0:
            enable()
```

The idea can be extended to allow flags on model instances (say, is_flag_active(request, 'new_store_ui', object=shop)). But just having a way to do custom decisions based on the request would be enough for now.

If this is accepted I can work on a patch.

**Comment by holvianssi** [comment] 2016-11-03 14:06
BTW an another approach is to register callbacks for specific flags. Something like this:

```
def new_login_for_internal_users(request, flag):
    return get_ip_from_request(request) in INTERNAL_IPS
waffle.add_callback('new_login', new_login_for_internal_users)
```

the add_callback definition would be:

```
callbacks = {}
def add_callback(flag_name, func):
    if flag_name not in callbacks:
        callbacks[flag_name] = []
    callbacks[flag_name].append(func)
```

and the actual usage in end of flag_is_active:

```
    for callback in callbacks.get(flag.name, ()):
        enabled = callback(request, flag)
        if enabled:
            return True
    return False
```

**Comment by jsocol** [comment] 2016-11-03 16:05
Im not likely to add first-class signals support but there's already an issue to provide abstract base classes, which is explicitly to allow this kind of customization for smaller use cases.

There's also an issue for adding IP ranges as conditions to the core type.

Would those changes provide enough flexibility to implement these kinds of things?

**Comment by holvianssi** [comment] 2016-11-04 05:44
Yeah, I think custom Flag classes would work if the decision logic of flag_is_active is moved to the flag class. Then could override is_active(request) in your concrete implementation.

I guess the biggest question is how does this play out with migrations - if you decide to change your flag implementation from Waffle's Flag, how exactly can you do this in an existing project?

I'd also like some possibility to provide context to is_active(). Basically this could be any object or dictionary. This would allow for all sorts of interesting logic. For example, if user has multiple tenants (say webshops), then you could enable/disable flag per tenant instead of per user. But I  guess this is a separate issue.

**Comment by holvianssi** [comment] 2016-11-04 06:45
I'm playing around with a fork where I have implemented the callbacks approach, and I must say I really like it. You can implement whatever logic you want for decisions without any need to override the Flag class. And the code changes in waffle are literally less than ten lines of code.

Of course, if the decision logic is moved to the Flag class, then the callbacks approach can be done in custom is_active method directly.

**Comment by jsocol** [comment] 2017-08-26 17:49
Duplicate of #181.

Ugh github's duplicate issue thing is finnicky.

Anyway, to add a longer comment, I think the official answer is going to be #181, but to answer your question about migrations:

1.0 is almost certainly going to have to be a major/breaking release and the upgrade path might not be super fun. Maybe we can make it easier via a export/import script but the tables aren't great and at some point we need to be able to fix that.

**Closed as completed by jsocol** 2017-08-26 17:49 UTC
