### ISSUE TITLE
override_flag doesn't affect template?

### ISSUE THREAD

**Issue by wasabigeek** [django-waffle/django-waffle#228] opened 2016-10-18 19:05 UTC
Hoping someone can shed light on this - with the following code:

Django Test

```
with override_flag('showNewCalc', active=True):
    response = self.client.get("/correct-url/")
    self.assertContains(response, 'href="{0}"'.format(correct_url))
```

HTML

```
<a href="{% flag 'showNewCalc' %}/correct-url/{% else %}{% url 'app.views.incorrect_url' %}{% endflag %}">
     LINK
</a>
```

The test sees the `incorrect_url`. Is that expected i.e. I can only use the override_flag with a view?

**Comment by jsocol** [comment] 2017-01-16 18:17
No, I would definitely expect `/correct-url/` in this case. Have you had any luck with this? Do you think you could write a test case (or a patch)?

**Comment by aarcro** [comment] 2017-06-05 17:14
I've hit an issue with override_flag just in my test cases. I think the issue is that it doesn't flush the cache. So even though I'm doing `@override_flag('flag', active=False)` in `pdb` I can check `waffle.models.Flag.get(name='flag').everyone` and it is `False` as expected. When I step into `waffle.flag_is_active` I see that it pulls the Flag from cache and `everyone == True`

**Comment by aarcro** [comment] 2017-06-05 18:04
Just checked out the code to make a PR for this, but maybe this was addressed? Master for version 12 looks like it's in a better shape than 11.1 that is out currently. Any chance of getting a release out soon?

**Comment by jsocol** [comment] 2017-08-26 17:59
0.12 was released a few weeks after this—going to go ahead and close it but please re-open if it's still an issue!

**Closed as completed by jsocol** 2017-08-26 17:59 UTC
